### ISSUE TITLE
Project Presentation

### ISSUE THREAD

**Issue by stanleyyoang** [panaman67/OOPProject#34]
Official deadline for the project is the last day of class, but Watson wants us to show him the project in class before submitting it, via Dropbox. Think we can be ready to present by next Wednesday to get it knocked out of the way?

**Comment by stanleyyoang** [comment]
Friday works too

**Comment by panaman67** [comment]
So its up to you guys what day works best. Ill open a GitHub issue when its complete so you guys can look over it.
